version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: canary
      POSTGRES_PASSWORD: canary
      POSTGRES_DB: canary
    ports: ["5432:5432"]
    healthcheck: { test: ["CMD-SHELL","pg_isready -U canary"], interval: 5s, retries: 20 }
  control-plane:
    build: ../apps/control-plane
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Db: Host=db;Port=5432;Database=canary;Username=canary;Password=canary
    depends_on: { db: { condition: service_healthy } }
    ports: ["8080:8080"]
