name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Optional but nice: restore local dotnet tools (for dotnet-format)
      - name: Restore dotnet tools
        run: |
          dotnet new tool-manifest --force
          dotnet tool install dotnet-format --version 8.*
          dotnet tool restore

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test (with coverage)
        run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/TestResults/**/coverage.cobertura.xml
            **/TestResults/**/test_results.trx

      - name: Check formatting (non-blocking on Day 1)
        run: dotnet format --verify-no-changes || echo "format drift (ok for Day 1)"
